[project]
name = "sleepscore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Graham Findlay", email = "graham.b.findlay@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "loupe @ git+https://github.com/CSC-UW/loupe.git@feature/better-labels",
    "xarray",
]

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"
